version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:2.14.2
    container_name: portainer
    restart: always

    environment:
      - VIRTUAL_HOST=${PORTAINER_HOST}
      - LETSENCRYPT_HOST=${PORTAINER_HOST}
      - VIRTUAL_PORT=9000

    networks:
      - ssl-network

networks:
  ssl-network:
    external: true
    name: ssl-network